/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingAiRouteImport } from './routes/writing-ai'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReadingRouteImport } from './routes/reading'
import { Route as ListeningRouteImport } from './routes/listening'
import { Route as IndexRouteImport } from './routes/index'

const WritingAiRoute = WritingAiRouteImport.update({
  id: '/writing-ai',
  path: '/writing-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoute = ReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeningRoute = ListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/listening': typeof ListeningRoute
  '/reading': typeof ReadingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking': typeof SpeakingRoute
  '/tasks': typeof TasksRoute
  '/writing': typeof WritingRoute
  '/writing-ai': typeof WritingAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/listening': typeof ListeningRoute
  '/reading': typeof ReadingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking': typeof SpeakingRoute
  '/tasks': typeof TasksRoute
  '/writing': typeof WritingRoute
  '/writing-ai': typeof WritingAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/listening': typeof ListeningRoute
  '/reading': typeof ReadingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking': typeof SpeakingRoute
  '/tasks': typeof TasksRoute
  '/writing': typeof WritingRoute
  '/writing-ai': typeof WritingAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/listening'
    | '/reading'
    | '/sitemap.xml'
    | '/speaking'
    | '/tasks'
    | '/writing'
    | '/writing-ai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/listening'
    | '/reading'
    | '/sitemap.xml'
    | '/speaking'
    | '/tasks'
    | '/writing'
    | '/writing-ai'
  id:
    | '__root__'
    | '/'
    | '/listening'
    | '/reading'
    | '/sitemap.xml'
    | '/speaking'
    | '/tasks'
    | '/writing'
    | '/writing-ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListeningRoute: typeof ListeningRoute
  ReadingRoute: typeof ReadingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeakingRoute: typeof SpeakingRoute
  TasksRoute: typeof TasksRoute
  WritingRoute: typeof WritingRoute
  WritingAiRoute: typeof WritingAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing-ai': {
      id: '/writing-ai'
      path: '/writing-ai'
      fullPath: '/writing-ai'
      preLoaderRoute: typeof WritingAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listening': {
      id: '/listening'
      path: '/listening'
      fullPath: '/listening'
      preLoaderRoute: typeof ListeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListeningRoute: ListeningRoute,
  ReadingRoute: ReadingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeakingRoute: SpeakingRoute,
  TasksRoute: TasksRoute,
  WritingRoute: WritingRoute,
  WritingAiRoute: WritingAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
